#%RAML 0.8
---
title: APIflow API
version: v1.0
baseUri: http://pf-staging.point.io
mediaType: application/json
documentation:
  - title: Introduction
    content: |
      API to use APIdoc items within a defined workflow
schemas:
  - processtypes: |
      {"type": "object",
       "$schema": "http://json-schema.org/draft-03/schema",
       "id": "http://jsonschema.net",
       "required": false,
       "properties": {
          "REQUEST": {
              "type": "object",
              "id": "http://jsonschema.net/REQUEST",
              "required": false,
              "properties": {
                  "ERR": {
                      "type": "number",
                      "id": "http://jsonschema.net/REQUEST/ERR",
                      "required": false
                  },
                  "PROCESSTYPES": {
                      "type": "array",
                      "id": "http://jsonschema.net/REQUEST/PROCESSTYPES",
                      "required": false,
                      "items": {
                          "type": "object",
                          "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0",
                          "required": false,
                          "properties": {
                              "BPMNXML": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/BPMNXML",
                                  "required": false
                              },
                              "category": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/category",
                                  "required": false
                              },
                              "deploymentId": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/deploymentId",
                                  "required": false
                              },
                              "description": {
                                  "type": "null",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/description",
                                  "required": false
                              },
                              "hasStartForm": {
                                  "type": "boolean",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/hasStartForm",
                                  "required": false
                              },
                              "id": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/id",
                                  "required": false
                              },
                              "isSuspended": {
                                  "type": "boolean",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/isSuspended",
                                  "required": false
                              },
                              "key": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/key",
                                  "required": false
                              },
                              "name": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/name",
                                  "required": false
                              },
                              "resourceName": {
                                  "type": "string",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/resourceName",
                                  "required": false
                              },
                              "version": {
                                  "type": "number",
                                  "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/version",
                                  "required": false
                              }
                          }
                      }
                  }
              }
          }
      }
      }


traits:
  - secured:
      description: Most requests require an authentication token
      queryParameters:
        Authorization:
          example: C74A497E7A5600C6...332FD

/tasks:
  get:
    responses:
      200:
  put:
    responses:
      200:

/processes:
  post:
    responses:
      200:
  get:
    responses:
      200:
  delete:
    responses:
      200:

/processtypes:
  post:
    responses:
      200:
  get:
    is: [ secured ]
    responses:
      200:
        body:
          application/json:
            schema: |
             {
             "type": "object",
             "$schema": "http://json-schema.org/draft-03/schema",
             "id": "http://jsonschema.net",
             "required": true,
             "properties": {
                "REQUEST": {
                    "type": "object",
                    "id": "http://jsonschema.net/REQUEST",
                    "required": true,
                    "properties": {
                        "ERR": {
                            "type": "number",
                            "id": "http://jsonschema.net/REQUEST/ERR",
                            "required": true
                        },
                        "PROCESSTYPES": {
                            "type": "array",
                            "id": "http://jsonschema.net/REQUEST/PROCESSTYPES",
                            "required": true,
                            "items": {
                                "type": "object",
                                "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0",
                                "required": false,
                                "properties": {
                                    "BPMNXML": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/BPMNXML",
                                        "required": true
                                    },
                                    "category": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/category",
                                        "required": true
                                    },
                                    "deploymentId": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/deploymentId",
                                        "required": true
                                    },
                                    "description": {
                                        "type": "null",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/description",
                                        "required": true
                                    },
                                    "hasStartForm": {
                                        "type": "boolean",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/hasStartForm",
                                        "required": true
                                    },
                                    "id": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/id",
                                        "required": true
                                    },
                                    "isSuspended": {
                                        "type": "boolean",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/isSuspended",
                                        "required": true
                                    },
                                    "key": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/key",
                                        "required": true
                                    },
                                    "name": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/name",
                                        "required": true
                                    },
                                    "resourceName": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/resourceName",
                                        "required": true
                                    },
                                    "version": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/REQUEST/PROCESSTYPES/0/version",
                                        "required": true
                                    }
                                }
                            }
                        }
                    }
                }
             }}

  delete:
    responses:
      200:

/messages:
  post:
    responses:
      200:

/datastore:
  get:
    is: [ secured ]
    responses:
      200:
        body:
          application/json:
            schema: |
            {
            	"type":"object",
            	"$schema": "http://json-schema.org/draft-03/schema",
            	"id": "http://point.io/datastoreResponse",
            	"required":true,
            	"properties":{
            		"items": {
            			"type":"array",
            			"id": "http://point.io/datastoreResponse/items",
            			"required":true,
            			"items":
            				{
            					"type":"object",
            					"id": #items/0",
            					"required":false
            				}


            		}
            	}
            }


  /{docId}:
    get:
      is: [ secured ]
      body:
        application/json:
        responses:
          200:
            body:
              application/json:
    post:
      is: [ secured ]
      body:
        application/json:
        responses:
          200:
            body:
              application/json:

    put:
      is: [ secured ]
      body:
        application/json:
        responses:
          200:
            body:
              application/json:

    patch:
      is: [ secured ]
      body:
        application/json:
        responses:
          200:
            body:
              application/json:
